name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        shell: bash
        run: bun install
      - name: Test
        shell: bash
        run: bun test
      - name: Days
        shell: bash
        # don't print to log to keep secret
        run: bun run start > /dev/null
